export { default as Footer } from './footer'
export { default as NavBar } from './navbar'
export { default as Hero } from './hero'
export { default as BreadCrumbs } from './breadcrumbs'
export { default as Modal } from './modal'
